const brands=[
{name:'Clear Men',duration:'2026 · Present',logo:'CLEAR MEN',project:'Global digital activation',description:'Brand management, digital campaign strategy, social media and content activation.',kpis:['100K+ followers','#1 worldwide ranking','Millions of impressions']},
{name:'Cheezy',duration:'2025 · 3 months',logo:'CHEEZY',project:'Brand & social activation',description:'Content management, community activation and social communication for the brand.',kpis:['+120 content pieces managed','High community engagement','Strong brand loyalty & interaction']},
{name:'Signal',duration:'2026 · Present',logo:'SIGNAL',project:'Social & creator-led communication',description:'Social media, content and creator-led storytelling designed to strengthen engagement.',kpis:['13.4K followers','Authentic community','Engaging content · positive impact']},
{name:'Bionnex',duration:'2026 · Present',logo:'BIONNEX',project:'Dermo-cosmetic brand management',description:'Brand communication, content planning and digital activation for a dermo-cosmetic portfolio.',kpis:['60+ content managed','Coherent feed','Engaged community · strong brand image']},
{name:'IFRI',duration:'2024 · 3 months',logo:'IFRI',project:'Influencer & content activation',description:'Influencer coordination and content management to amplify brand visibility.',kpis:['+20 influencers collaborated','+60 content managed','Millions of views generated']},
{name:'LG',duration:'2025 · 3 months',logo:'LG',project:'Digital & UGC activation',description:'Content management, engagement and creator-generated content activation.',kpis:['100+ content managed','High engagement','15+ UGC profiles managed']},
{name:'Facteur X',duration:'Present',logo:'FACTEUR X',project:'Digital communication',description:'Full communication support across content, social media and digital activation.',kpis:['Full project ownership','Multi-format content','End-to-end execution']},
{name:"Festival des Sports d'Alger",duration:'2026 · One-off',logo:'FESTIVAL DES SPORTS',project:'High-volume event communication',description:'Fast-paced social media and content execution during a concentrated event period.',kpis:['150 content posted','3 days of full rush','Strong engagement']}
];
const track=document.querySelector('#brandTrack'),dots=document.querySelector('#dots'),projects=document.querySelector('#projects');
track.innerHTML=brands.map((b,i)=>`<article class="brand-card" data-i="${i}" tabindex="0"><div class="brand-logo">${b.logo}</div><div class="name">${b.name}</div><div class="duration">${b.duration}</div><div class="kpis"><strong>${b.duration}</strong><small>${b.kpis.join(' · ')}</small></div></article>`).join('');
dots.innerHTML=brands.map((_,i)=>`<button data-i="${i}" aria-label="Brand ${i+1}"></button>`).join('');
projects.innerHTML=brands.map((b,i)=>`<article class="project" id="project-${i}"><div class="project-visual"><strong>${b.logo}</strong></div><div class="project-info"><div class="project-meta"><span>${String(i+1).padStart(2,'0')} / ${brands.length}</span><span>${b.duration}</span></div><h3>${b.project}</h3><p>${b.description}</p><div class="kpi-grid">${b.kpis.map(k=>{const parts=k.split(' ');return `<div class="kpi-item"><strong>${parts.slice(0,2).join(' ')}</strong><span>${parts.slice(2).join(' ')||'Performance highlight'}</span></div>`}).join('')}</div></div></article>`).join('');
let current=0;function update(){const card=document.querySelector('.brand-card');if(!card)return;const gap=18,w=card.getBoundingClientRect().width+gap,visible=innerWidth<=900?1:4,max=Math.max(0,brands.length-visible);current=Math.max(0,Math.min(current,max));track.style.transform=`translateX(-${current*w}px)`;[...dots.children].forEach((d,i)=>d.classList.toggle('active',i===current))}document.querySelector('#prev').onclick=()=>{current--;update()};document.querySelector('#next').onclick=()=>{current++;update()};dots.onclick=e=>{if(e.target.dataset.i){current=+e.target.dataset.i;update()}};document.querySelectorAll('.brand-card').forEach(c=>{const go=()=>document.querySelector('#project-'+c.dataset.i)?.scrollIntoView({behavior:'smooth'});c.onclick=go;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')go()}});addEventListener('resize',update);update();
const burger=document.querySelector('#burger');burger.onclick=()=>{const nav=document.querySelector('nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='82px';nav.style.left='0';nav.style.right='0';nav.style.padding='25px 20px';nav.style.background='#f4f1e9';nav.style.flexDirection='column'};
